### ISSUE TITLE
dll file version numbers

### ISSUE THREAD

**Issue by brmiranda** [LANDIS-II-Foundation/Extension-Output-Max-Species-Age#10]
Landis.Extension.Output.MaxSpeciesAge-v3.dll installs with File Version of 7.0.0.0 and Product Version of 1.0.0.  Given the v3 name of the file, both should be 3.0.

**Comment by rmscheller** [comment]
Thanks, Brian!  I greatly appreciate your keen eye.  New version released as replacement, given the minimal changes.
